import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy & Disclaimers | Ramesh Nuti",
  description:
    "Legal terms, disclaimers, and privacy policy for RameshNuti.com. All tools and information are provided as-is without warranties.",
  alternates: {
    canonical: "https://rameshnuti.com/privacy",
  },
};

export default function PrivacyPage() {
  return (
    <div className="bg-white min-h-screen text-slate-900 font-sans">
      {/* Hero Header */}
      <section className="bg-slate-light border-b border-slate-100 py-16 px-6">
        <div className="max-w-3xl mx-auto text-left space-y-4">
          <span className="inline-block bg-slate-200 text-slate-700 px-3 py-1 rounded-full text-xs font-mono font-bold tracking-wider uppercase">
            ⚖️ LEGAL TERMS
          </span>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-slate-900">
            Privacy Policy &amp; Disclaimers
          </h1>
          <p className="text-slate-600 text-sm md:text-base max-w-xl leading-relaxed">
            Please read these terms carefully. By using this website, you agree to these disclaimers and limitations of liability.
          </p>
        </div>
      </section>

      {/* Legal Content */}
      <section className="py-16 px-6 bg-white">
        <div className="max-w-3xl mx-auto text-left space-y-12">
          
          {/* Section 1: As-Is Warranties */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-slate-900 tracking-tight">1. &ldquo;As-Is&rdquo; Provision</h2>
            <p className="text-slate-600 text-sm leading-relaxed">
              All information, code, software, interactive calculators, and analytical tools (including but not limited to the <em>SpaceX IPO Investment Simulator</em> and the <em>Steelman the Opposition</em> tool) provided on this website are distributed on an <strong>&ldquo;as-is&rdquo; and &ldquo;as-available&rdquo; basis</strong>, without warranties or guarantees of any kind, either express or implied. 
            </p>
            <p className="text-slate-600 text-sm leading-relaxed">
              We do not warrant that the website will be uninterrupted, error-free, secure, or free from inaccuracies, or that any output generated by the interactive tools will match real-world financial or strategic outcomes.
            </p>
          </div>

          {/* Section 2: No Investment Advice */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-slate-900 tracking-tight">2. No Investment or Professional Advice</h2>
            <p className="text-slate-600 text-sm leading-relaxed">
              Nothing on this website constitutes financial, investment, accounting, legal, or other professional advice. The calculators, simulators, and guides are intended solely for <strong>educational, simulation, and informational purposes</strong>. 
            </p>
            <p className="text-slate-600 text-sm leading-relaxed">
              Past performance is not indicative of future results. You should consult a licensed financial advisor, legal professional, or relevant certified specialist before making any high-risk business, investing, or operational decisions.
            </p>
          </div>

          {/* Section 3: Limitation of Liability */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-slate-900 tracking-tight">3. Limitation of Liability</h2>
            <p className="text-slate-600 text-sm leading-relaxed">
              To the maximum extent permitted by applicable law, <strong>Ramesh Nuti shall not be liable</strong> for any direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to damages for loss of profits, investment losses, data loss, business interruption, or other intangible losses arising out of or in connection with:
            </p>
            <ul className="list-disc list-inside pl-4 text-slate-600 text-sm space-y-2">
              <li>Your use of, or inability to use, this website or its tools.</li>
              <li>Any decision made or action taken by you in reliance upon the outputs, metrics, predictions, or opinions generated on this site.</li>
              <li>Any unauthorized access to or alteration of your communications or newsletter registration inputs.</li>
            </ul>
          </div>

          {/* Section 4: Privacy Policy & Cookies */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-slate-900 tracking-tight">4. Privacy Policy</h2>
            <p className="text-slate-600 text-sm leading-relaxed">
              Your privacy is important to us. This section explains how we handle data:
            </p>
            <ul className="list-disc list-inside pl-4 text-slate-600 text-sm space-y-2">
              <li>
                <strong>Newsletter Registrations:</strong> When you enter your email to subscribe to the newsletter or download workshop materials, your data is processed directly by <strong>Substack</strong>. We do not store your email addresses in our local database. Substack&apos;s privacy policy and terms of service govern your subscription data.
              </li>
              <li>
                <strong>No Data Selling:</strong> We will never sell, lease, or distribute your email address to third parties. We may occasionally send you relevant updates or resources about sibling projects in our startup ecosystem (such as playwithprompts.com), which you can opt-out of at any time.
              </li>
              <li>
                <strong>Analytics &amp; Usage Data:</strong> We may collect anonymized usage details (such as page views or general tool interactions) to improve website performance and user experience.
              </li>
              <li>
                <strong>Data Security:</strong> We utilize HTTPS and standard encryption protocols to protect inputs sent to our forms.
              </li>
            </ul>
          </div>

          {/* Section 5: Sister Properties & Third-Party Platforms */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-slate-900 tracking-tight">5. Sister Properties &amp; Third-Party Platforms</h2>
            <p className="text-slate-600 text-sm leading-relaxed">
              This website contains links to other digital properties owned or operated by Ramesh Nuti (such as <strong>Svyam Ventures</strong>, <strong>ActionEDI</strong>, and <strong>playwithprompts.com</strong>), as well as third-party host platforms like <strong>Substack</strong> and <strong>Replit</strong>.
            </p>
            <p className="text-slate-600 text-sm leading-relaxed">
              While these sister sites are part of our ecosystem, they operate under their own individual terms of use, operational guidelines, and privacy practices. Transactions or agreements entered into on those platforms are subject to their respective terms, and we accept no liability for any outcomes, data processing, or operations conducted on those separate domains.
            </p>
          </div>

          {/* Bottom Action */}
          <div className="pt-8 border-t border-slate-100 flex justify-between items-center text-xs">
            <span className="text-slate-400">Last updated: May 25, 2026</span>
            <Link
              href="/"
              className="text-teal-accent font-bold no-underline hover:underline"
            >
              Return Home &rarr;
            </Link>
          </div>

        </div>
      </section>
    </div>
  );
}
